/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lockSol from "./Lock.sol";
export type { lockSol };
export type { ToDoList } from "./ToDoList";
export * as factories from "./factories";
export type { ToDoList } from "./Lock.sol/ToDoList";
export { ToDoList__factory } from "./factories/Lock.sol/ToDoList__factory";
